services:
  - type: web
    name: fw-code-check-web-service
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:10000 app:app"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
    autoDeploy: true
    buildFilter:
      paths:
        - src/python/**
        - requirements.txt
    rootDir: src/python
  - type: static
    name: fw-code-check-web
    env: static
    buildCommand: "npm install && npm run build"
    staticPublishPath: public
    envVars:
      - key: REACT_APP_API_URL
        value: https://fw-code-check-web-service.onrender.com/api/analyze
    autoDeploy: true
    buildFilter:
      paths:
        - src/renderer/**
        - package.json
        - webpack.config.js
        - tailwind.config.js
        - public/**
